### PR TITLE
Fix all the Next.js warning and errors in the console

### LINKED ISSUE #1593: Fix all the Next.js warning and errors in the console
The console is full of warnings and errors. It's time to fix them to understand when we actually have a problem.

### PR DESCRIPTION
**Pull request by clacladev**
**What does this pull request do? Explain your changes. (required)**
Fix all the Next.js warning and errors in the console

**Does this pull request close any open issues?**
Fixes #1593

### CODE REVIEW

File: packages/www/layouts/dashboard.tsx [hunk 1]
```diff
@@ -58,6 +58,8 @@ function DashboardLayout({
   canonical,
   requireLoggedIn = true,
 }: Props) {
+  const [stripePromise] = useState(() => getStripe());
```
Comment (0xcadams) [inline packages/www/layouts/dashboard.tsx]: `useMemo` might be a better fit here

**Review by 0xcadams — APPROVED** [review]
