### PR TITLE
validateAssetMeta merges any existing asset meta

### LINKED ISSUE #1229: Updating meta in VoD overrides existing fields
**Describe the bug (required)** A clear and concise description of what the bug
is.
When updating the metadata field for an asset, existing metadata fields get replaced by the updated ones.

**Expected behavior (required)** A clear and concise description of what you
expected to happen.

Expect to only update the metadata fields provided by the user and keep existing ones

**To Reproduce (required)** Steps to reproduce the behavior:

1. Create an asset
2. Update the asset with a new meta field using `PATCH`
3. Get the asset
4. Update the same asset with a different meta field using `PATCH` again
5. Get the asset and see the first meta field gone

**Device (required):**

- Device: MacBook Pro
- OS: macOS Monterey v 12.5
- Browser: Chrome
- Version: 104.0.5112.101 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by Shih-Yu**
**What does this pull request do? Explain your changes. (required)**

Addressing the issue https://github.com/livepeer/studio/issues/1229

**Specific updates (required)**

Change validateAssetMeta function to merge with any existing meta

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: packages/api/src/controllers/asset.ts [hunk 1]
```diff
@@ -47,7 +47,10 @@ const app = Router();
 
 const META_MAX_SIZE = 1024;
 
-function validateAssetMeta(meta: Record<string, string>) {
+function validateAssetMeta( meta: Record<string, string>, asset?:WithID<Asset> ) {
```
Comment (victorges) [inline packages/api/src/controllers/asset.ts]: Apparently the prettier is still not working on your env. Run `yarn prettier` manually from the project root instead.

File: packages/api/src/controllers/asset.ts [hunk 2]
```diff
@@ -47,7 +47,10 @@ const app = Router();
...
+  meta = _({ ...asset.meta, ...meta })
```
Comment (victorges) [inline packages/api/src/controllers/asset.ts]: The asset is not always available so this needs to be `?.`
```suggestion
  meta = _({ ...asset?.meta, ...meta })
```

File: packages/api/src/controllers/asset.ts [hunk 3]
```diff
@@ -47,7 +47,10 @@ const app = Router();
...
+            .omit(_.isNull)
```
Comment (victorges) [inline packages/api/src/controllers/asset.ts]: This does not "compile". You need to fix your typescript env and pay attention to the errors it shows. The correct function to call here is `omitBy` (but you also need to test it)
Screen Shot 2022-08-26 at 17 38 33

File: packages/api/src/controllers/asset.ts [hunk 4]
```diff
@@ -816,12 +820,13 @@ app.patch(
...
     // update a specific asset
     const { id } = req.params;
-    const asset = await db.asset.get(id);
+    const asset = await db.asset.get( id );
     if (!asset || (asset.userId !== req.user.id && !req.user.admin)) {
       throw new NotFoundError(`asset not found`);
     } else if (asset.status.phase !== "ready") {
       throw new UnprocessableEntityError(`asset is not ready`);
     }
+    validateAssetMeta(meta, asset);
```
Comment (victorges) [inline packages/api/src/controllers/asset.ts]: The return value of this function is being ignored. It is also not the only place where this is called. Anytime you change the behavior of a function you need to update everywhere it is used. So keep that in mind and look for the other usages in the code.

**Review by victorges — CHANGES_REQUESTED** [review]
You should also add some unit tests for this feature as I believe you have not exercised the code to make sure it works (right now it does not). 

The tests would go around here (as separate `it`s): https://github.com/livepeer/livepeer-com/blob/845e074c9f755e876bb23db83b374901d4c68842/packages/api/src/controllers/asset.test.ts#L218

You should add some cases like: 
 - Allows adding `meta` to an asset
 - Allows adding fields to an existing `meta` in an `asset`
 - Allows removing a filed from the `meta` by setting it to `null`
 - Disallows any update that would result in a meta greater than that `META_MAX_SIZE` (incl if it only hits max size after the merge)

File: packages/api/src/controllers/asset.ts (hunk 4 above)
Comment (victorges) [reply packages/api/src/controllers/asset.ts]: Actually... This function is **already** being called in this API handler. You should call it only **once**. No reason to call it again. Remove this line and edit the original call instead.

**Review by victorges — APPROVED** [review]
LGTM!
