### PR TITLE
Issue #664 Windows Display Bug -- credit card input field

### LINKED ISSUE #664: Windows Display Bug -- credit card input field
When using a Windows computer, it looks like the credit card input field is in dark mode when the rest of the page is in light mode. 

I'd expect the credit card input field to obey the light/dark theme preference. 

(apologies for this horrible photo of a screen, I was too lazy to figure out how to screenshot on a windows computer)

### PR DESCRIPTION
**Pull request by FullStackTiger**
**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- fixed init theme mode issue on the credit card input field

**Does this pull request close any open issues?**

- Fixes #664

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: packages/www/layouts/dashboard.tsx [hunk 1]
```diff
@@ -79,7 +79,7 @@ function ContextProviders({ children }) {
         <ThemeProvider
           disableTransitionOnChange
           attribute="class"
-          defaultTheme="system"
+          defaultTheme="dark"
```
Comment (adamsoffer) [inline packages/www/layouts/dashboard.tsx]: This value should remain `system` as we want to the dashboard to inherit the theme settings on a user's system whether that's light or dark mode. Is there another way we can force the stripe input component to inherit the current theme?

**Review by adamsoffer — CHANGES_REQUESTED** [review]

**Review by adamsoffer — APPROVED** [review]
Nice. Looks good.
